<a href="https://colab.research.google.com/github/Kosuri069/IIT-Patna/blob/main/Pandas_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

data = {
    'transaction_id': range(1, 21),
    'date': pd.date_range('2024-10-01', periods=20, freq='D'),
    'region': ['North', 'South', 'East', 'West', None, 'North', 'South', None, 'East', 'West',
               'North', 'South', 'East', 'West', 'North', None, 'East', 'West', 'North', 'South'],
    'product_category': ['Electronics', 'Clothing', None, 'Books', 'Electronics', 'Home',
                         'Clothing', 'Books', 'Electronics', None, 'Home', 'Clothing',
                         'Books', 'Electronics', 'Home', 'Clothing', 'Books', 'Electronics',
                         'Home', 'Clothing'],
    'sales_amount': [1200, 450, 890, None, 1500, 670, None, 340, 2100, 780,
                     560, None, 420, 1800, 920, 510, 380, None, 1100, 640],
    'quantity': [2, 5, 3, 1, None, 4, 2, 3, 1, 5,
                 3, 2, None, 1, 4, 3, 2, 1, None, 4],
    'customer_age': [25, 34, None, 45, 29, None, 38, 52, 27, 41,
                     33, None, 48, 26, 35, 42, None, 31, 39, 44],
    'payment_method': ['Credit Card', 'UPI', 'Cash', 'Debit Card', 'Credit Card',
                       'UPI', 'Cash', None, 'Credit Card', 'UPI', 'Debit Card',
                       'Cash', 'Credit Card', None, 'UPI', 'Cash', 'Debit Card',
                       'Credit Card', 'UPI', None]
}

df = pd.DataFrame(data)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    20 non-null     int64
 1   date              20 non-null     datetime64[ns]
 2   region            17 non-null     object
 3   product_category  18 non-null     object
 4   sales_amount      16 non-null     float64
 5   quantity          17 non-null     float64
 6   customer_age      16 non-null     float64
 7   payment_method    17 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.4+ KB

In [9]:
df.isna().sum()

transaction_id      0
date                0
region              3
product_category    2
sales_amount        4
quantity            3
customer_age        4
payment_method      3
dtype: int64

In [10]:
df['region'] = df['region'].fillna(df['region'].mode()[0])

In [11]:
df['product_category'] = df['product_category'].fillna(df['product_category'].mode()[0])

In [12]:
df['sales_amount'] = df['sales_amount'].fillna(df['sales_amount'].median())

In [13]:
df['quantity'] = df['quantity'].ffill()

In [14]:
df['customer_age'] = df['customer_age'].fillna(round(df['customer_age'].mean()))

In [15]:
df.isna().sum()

transaction_id      0
date                0
region              0
product_category    0
sales_amount        0
quantity            0
customer_age        0
payment_method      3
dtype: int64

In [16]:
sales_by_region = df.groupby('region')['sales_amount'].sum()
print(sales_by_region)

region
East     3790.0
North    6800.0
South    2540.0
West     4030.0
Name: sales_amount, dtype: float64

In [17]:
avg_sales_category = df.groupby('product_category')['sales_amount'].mean()
print(avg_sales_category)

product_category
Books           466.250000
Clothing        674.285714
Electronics    1465.000000
Home            812.500000
Name: sales_amount, dtype: float64

In [18]:
region_product_summary = df.groupby(['region','product_category']).agg({
    'sales_amount':'sum',
    'quantity':'sum'
}).reset_index()

print(region_product_summary)

   region product_category  sales_amount  quantity
0    East            Books         800.0       4.0
1    East         Clothing         890.0       3.0
2    East      Electronics        2100.0       1.0
3   North            Books         340.0       3.0
4   North         Clothing         510.0       3.0
5   North      Electronics        2700.0       3.0
6   North             Home        3250.0      12.0
7   South         Clothing        2540.0      13.0
8    West            Books         725.0       1.0
9    West         Clothing         780.0       5.0
10   West      Electronics        2525.0       2.0

In [19]:
top3 = region_product_summary.sort_values(by='sales_amount', ascending=False).head(3)
print(top3)

  region product_category  sales_amount  quantity
6  North             Home        3250.0      12.0
5  North      Electronics        2700.0       3.0
7  South         Clothing        2540.0      13.0

In [20]:
def sales_range(x):
    return x.max() - x.min()

In [21]:
range_by_region = df.groupby('region')['sales_amount'].apply(sales_range)
print(range_by_region)

region
East     1720.0
North    1160.0
South     275.0
West     1075.0
Name: sales_amount, dtype: float64

In [22]:
region_metrics = df.groupby('region').agg({
    'sales_amount':['sum','mean','max'],
    'quantity':['sum','min']
})

print(region_metrics)

       sales_amount                 quantity
                sum    mean     max      sum  min
region
East         3790.0   947.5  2100.0      8.0  1.0
North        6800.0   850.0  1500.0     21.0  1.0
South        2540.0   635.0   725.0     13.0  2.0
West         4030.0  1007.5  1800.0      8.0  1.0