In [1]:
import pandas as pd

data = [
    {"EmployeeID": 201, "Name": "Sarah",    "Department": "Engineering", "Salary": 85000, "Performance Score": 4, "Years of Service": 5},
    {"EmployeeID": 202, "Name": "Michael",  "Department": "Sales",       "Salary": 62000, "Performance Score": 3, "Years of Service": 3},
    {"EmployeeID": 203, "Name": "Jennifer", "Department": "Marketing",   "Salary": 71000, "Performance Score": 5, "Years of Service": 7},
    {"EmployeeID": 204, "Name": "David",    "Department": "Engineering", "Salary": 92000, "Performance Score": 5, "Years of Service": 8},
    {"EmployeeID": 205, "Name": "Lisa",     "Department": "HR",          "Salary": 58000, "Performance Score": 4, "Years of Service": 4},
    {"EmployeeID": 206, "Name": "James",    "Department": "Sales",       "Salary": 68000, "Performance Score": 4, "Years of Service": 6},
    {"EmployeeID": 207, "Name": "Emma",     "Department": "Engineering", "Salary": 78000, "Performance Score": 3, "Years of Service": 2},
    {"EmployeeID": 208, "Name": "Robert",   "Department": "Marketing",   "Salary": 75000, "Performance Score": 4, "Years of Service": 5},
    {"EmployeeID": 209, "Name": "Sophia",   "Department": "Sales",       "Salary": 65000, "Performance Score": 5, "Years of Service": 4},
    {"EmployeeID": 210, "Name": "William",  "Department": "HR",          "Salary": 60000, "Performance Score": 3, "Years of Service": 3},
]

employees_df = pd.DataFrame(data)
employees_df

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
1,202,Michael,Sales,62000,3,3
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
4,205,Lisa,HR,58000,4,4
5,206,James,Sales,68000,4,6
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5
8,209,Sophia,Sales,65000,5,4
9,210,William,HR,60000,3,3

In [2]:
employees_df[["Name", "Department", "Salary"]]

       Name   Department  Salary
0     Sarah  Engineering   85000
1   Michael        Sales   62000
2  Jennifer    Marketing   71000
3     David  Engineering   92000
4      Lisa           HR   58000
5     James        Sales   68000
6      Emma  Engineering   78000
7    Robert    Marketing   75000
8    Sophia        Sales   65000
9   William           HR   60000

In [3]:
employees_df.iloc[5]

EmployeeID             206
Name                 James
Department           Sales
Salary               68000
Performance Score        4
Years of Service         6
Name: 5, dtype: object

In [4]:
employees_by_id = employees_df.set_index("EmployeeID")
employees_by_id.loc[208]

Name                    Robert
Department           Marketing
Salary                   75000
Performance Score            4
Years of Service             5
Name: 208, dtype: object

In [5]:
employees_df.loc[employees_df["EmployeeID"] == 208]

   EmployeeID    Name Department  Salary  Performance Score  Years of Service
7         208  Robert  Marketing   75000                  4                 5

In [6]:
employees_df[employees_df["Department"] == "Engineering"]

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
0         201  Sarah  Engineering   85000                  4                 5
3         204  David  Engineering   92000                  5                 8
6         207   Emma  Engineering   78000                  3                 2

In [7]:
employees_df[employees_df["Salary"] > 70000]

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5

In [8]:
employees_df.sort_values("Salary", ascending=False).head(3)

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
3         204  David  Engineering   92000                  5                 8
0         201  Sarah  Engineering   85000                  4                 5
6         207   Emma  Engineering   78000                  3                 2

In [9]:
employees_df.sort_values(["Department", "Salary"], ascending=[True, False])

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
3,204,David,Engineering,92000,5,8
0,201,Sarah,Engineering,85000,4,5
6,207,Emma,Engineering,78000,3,2
9,210,William,HR,60000,3,3
4,205,Lisa,HR,58000,4,4
7,208,Robert,Marketing,75000,4,5
2,203,Jennifer,Marketing,71000,5,7
5,206,James,Sales,68000,4,6
8,209,Sophia,Sales,65000,5,4
1,202,Michael,Sales,62000,3,3